### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by msa21974** [edoost/pert#1]
It seems you have processed the original data. Could you please add dataset (bijankhan_corpus.tsv) to repository?

**Comment by edoost** [comment]
The data could easily be converted to the required format, which is a tab separated text file with `word`, `pos_tag` and `ezafe_tag` as columns, and tokens as rows. You should leave one empty line between each sentence. The ezafe tag, `GEN` in the 10 million word Bijankhan corpus, should be converted to `0` or `1`. As for the POS tags, you should only keep the coarse-grained tags, as described in the paper.
