### ISSUE TITLE
Ezafe tags in Bijankhan corpus

### ISSUE THREAD

**Issue by rezareza007** [edoost/pert#2]
Hi, the Bijankhan corpus that is available from Tehran University does not include ezafe tags, only POS tags. I wonder what version of the corpus you used exactly. Thanks.

**Comment by edoost** [comment]
Hi! We used the 10-million-word Bijankhan corpus (not the publicly available 2.5 million-word one), as stated in the paper. Please, contact the authors to get access to the corpus.
